"""initial schema

Revision ID: 42e611719621
Revises: 
Create Date: 2026-08-04 12:36:24.069022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e611719621'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('leetcode_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('pattern_key', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('examples', sa.JSON(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('function_signature', sa.JSON(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problems_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_problems_leetcode_id'), ['leetcode_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_problems_pattern_key'), ['pattern_key'], unique=False)

    op.create_table('user_stats',
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('solved_count', sa.Integer(), nullable=False),
    sa.Column('total_time_ms', sa.Integer(), nullable=False),
    sa.Column('last_solved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('weak_topics', sa.JSON(), nullable=False),
    sa.Column('strong_topics', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('problem_slug', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('time_ms', sa.Integer(), nullable=True),
    sa.Column('first_try', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['problem_slug'], ['problems.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempts_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_problem_slug'), ['problem_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_status'), ['status'], unique=False)

    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('problem_slug', sa.String(length=255), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('box', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['problem_slug'], ['problems.slug'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flashcards_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flashcards_problem_slug'), ['problem_slug'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('problem_slug', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['problem_slug'], ['problems.slug'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_problem_slug'), ['problem_slug'], unique=False)

    op.create_table('revisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('problem_slug', sa.String(length=255), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['problem_slug'], ['problems.slug'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revisions_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revisions_problem_slug'), ['problem_slug'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revisions_problem_slug'))
        batch_op.drop_index(batch_op.f('ix_revisions_device_id'))

    op.drop_table('revisions')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_problem_slug'))
        batch_op.drop_index(batch_op.f('ix_notes_device_id'))

    op.drop_table('notes')
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flashcards_problem_slug'))
        batch_op.drop_index(batch_op.f('ix_flashcards_device_id'))

    op.drop_table('flashcards')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempts_status'))
        batch_op.drop_index(batch_op.f('ix_attempts_problem_slug'))
        batch_op.drop_index(batch_op.f('ix_attempts_device_id'))

    op.drop_table('attempts')
    op.drop_table('user_stats')
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problems_pattern_key'))
        batch_op.drop_index(batch_op.f('ix_problems_leetcode_id'))
        batch_op.drop_index(batch_op.f('ix_problems_difficulty'))

    op.drop_table('problems')
    # ### end Alembic commands ###
